### ISSUE TITLE
Package this as a library?

### ISSUE THREAD

**Issue by magnusjonsson** [jhjourdan/C11parser#14]
I've long been looking for an ocaml equivalent of the parsing and AST parts of Haskell's excellent Language.C module, so this package looks very interesting to me. C.f. http://hackage.haskell.org/package/language-c-0.8.2/docs/Language-C-Syntax-AST.html

However, I'm confused as to how this code is supposed to be used. The readme suggests modifying the parser actions, but doesn't this mean every user has to maintain their own modified copy of the parser?

Thanks!

**Comment by jhjourdan** [comment]
The goal of this repository is to provide an implementation of a C parser which is compliant with the standard and sufficiently simple so that it can be easily be reused in other contexts. It is not supposed to be a C front-end library.

There are several reasons for this:
- I am not personally developing a tool that would be a user for this. Making this package a library would therefore cost me a lot of time for nothing, and the choices I would be doing will not be guided by use and may end up weird for an actual user. 
- My opinion is that it is very hard to have a C parser as a library that would suit the needs of all users: Perhaps your tool needs to extend the input language with some source-level annotations to perform analysis of input code, or perhaps you want to precisely keep track of source code locations and comments in order to be able to reconstruct the code. That's why I am providing a "parser skeleton" that one can use in order to write her own parser for her own tool that will suit her needs.
- In order to keep this code easier to re-use, I am trying to keep it simple to read and understand (including for a non OCaml specialist)

If you are looking for such a library in OCaml, then you can have a look at [CIL](https://cil-project.github.io/cil/). CIL is more complete than this project: It supports some C extensions and has an API with several C ASTs you can play with. However, its parser has been written before `C11parser` and therefore contains various bugs that would require some refactoring to solve. (Note, however, that the Haskell library you are referring to is not better wrt. compliance to the standard. Just run our test suite to see.)

**Comment by magnusjonsson** [comment]
Thanks for the explanation! I’ve considered and tried to use CIL in the past but found it came with too many assumptions and was hard to work with due to its frameworks nature. That speaks to your point I guess. I am using attributes to annnotate the source code for the static analysis I am doing so in my case I don’t need to extend the grammar. Thanks again! So for now my options are still Haskell with language.c and another option I’m exploring: writing my analysis as a gcc plugin.
